HW05 is complete
powerdigital/otus-golang pull request #5
Opened 2022-01-12 21:53 UTC by powerdigital

## Домашнее задание №5 «Параллельное исполнение»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я сравнил объем кода с объемом авторского решения. [Зачем сверять объем кода?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D1%81%D0%B2%D0%B5%D1%80%D1%8F%D1%82%D1%8C-%D0%BE%D0%B1%D1%8A%D0%B5%D0%BC-%D0%BA%D0%BE%D0%B4%D0%B0)
  - run.go ~55 строк

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2022-01-14 15:52 UTC, agneum requested changes
Спасибо за вариант решения.
Хорошая работа, однако решением не обеспечивается конкурентность исполнения. Возвращаю задачу на доработку

Итого: 4 балла из 10

2022-01-14 15:52 UTC, agneum commented on hw05_parallel_execution/run.go
> +type Task func(ch chan int32) error
Сигнатура функции не должна меняться, т.к. нет гарантий на то, что внутри каждой переданной функции аргумент будет определённым(корректным) образом обработан

2022-01-14 15:52 UTC, agneum commented on hw05_parallel_execution/run.go
> +			wg.Done()
Декремент индекса waitGroup происходит до того, как задача завершилась. Это означает, что функция `Run` не будет дожидаться окончания работы всех задач

2022-01-14 15:52 UTC, agneum commented on hw05_parallel_execution/run.go
> +			go task(ch)
Запускать новую горутину под каждую задачу выглядит неоптимально. Гораздо выгоднее запустить n-горутин обработчиков, которые через канал будут получать задачи(функции) и запускать их

2022-01-14 15:52 UTC, agneum commented on hw05_parallel_execution/run.go
> +		for i := 0; i < n; i++ {
Такой запуск не гарантирует конкурентного исполнения n-горутин. Кроме того, следует учитывать, что задачи могут выполняться разное время

2022-01-14 19:27 UTC, powerdigital commented on hw05_parallel_execution/run.go
> +		for i := 0; i < n; i++ {
но ведь это классический способ запустить несколько горутин в цикле!
я не встречал на наших лекциях, да и не нашел в инете другого способа.
либо я не понял комментария.

2022-01-14 19:27 UTC, powerdigital commented on hw05_parallel_execution/run.go
> +			wg.Done()
перенес ниже

2022-01-14 19:30 UTC, powerdigital commented on hw05_parallel_execution/run.go
> +type Task func(ch chan int32) error
к сожалению пока не вижу другого способа, как Run() может узнать о количестве ошибок, полученных в результате запуска функций, кроме как через взаимодействие с использованием каналов. может наведете на мысль?

2022-01-15 15:33 UTC, agneum commented on hw05_parallel_execution/run.go
> +type Task func(ch chan int32) error
Функция `Task` в явном виде возвращает `error`. Если возвращаемое значение `!= nil`, значит в результате запуска произошла ошибки

2022-01-15 15:41 UTC, agneum commented on hw05_parallel_execution/run.go
> +			wg.Done()
Перенос не решит проблему, декремент по-прежнему с высокой вероятностью произойдёт до того, как задача завершит выпонение. 

При использовании ключевого слова `go` код функции не выполняется линейно

2022-01-15 15:47 UTC, agneum commented on hw05_parallel_execution/run.go
> +		for i := 0; i < n; i++ {
При такой записи запустятся сразу все функции из слайса `tasks`.

По условию задания необходимо запустить не более `n` одновременно. И следующая задача должна запуститься как только выполнится одна из предыдущих. Таким образом получается, что в любой момент времени работают не более `n ` задач

2022-01-17 08:21 UTC, powerdigital commented on hw05_parallel_execution/run.go
> +			wg.Done()
ну тогда как быть, если мы не можем изменять сигнатуру функций, доступа в их тело мы стало быть не имеем, как мы можем контролировать вызов декремента, намекаете на defer?

2022-01-17 08:31 UTC, powerdigital commented on hw05_parallel_execution/run.go
> +type Task func(ch chan int32) error
но позвольте спросить, как мы можем получить возвращаемый функцией ответ, если она запущена как горутина?
разве мы можем делать так: `x := go task()`

2022-01-17 14:44 UTC, powerdigital commented on hw05_parallel_execution/run.go
> +			go task(ch)
не совсем понял предлагаемого решения. можно ли сориентировать в подходе?

2022-01-18 14:09 UTC, agneum commented on hw05_parallel_execution/run.go
> +type Task func(ch chan int32) error
Можно обернуть вызов `task` другой функцией, которая будет запущена как горутина:
```go
go func(){
    if err := task(); err != nil {
        ...
    }
}
```

2022-01-18 14:13 UTC, agneum commented on hw05_parallel_execution/run.go
> +			wg.Done()
При текущей имлементации `defer` не поможет. Необходимо изменить способ обработки задач так, чтобы гарантированно вызвать `Done` после завершения функции `task`.
Доступа внутрь функции действительно нет, но есть возможность управлять waitGroup снаружи, как в примере выше - оборачивая фукнции-задачи.

2022-01-18 14:20 UTC, agneum commented on hw05_parallel_execution/run.go
> +			go task(ch)
В данной задаче можно адаптировать подход `worker pool`: запустить n-горутин, внутри каждой из которых будет запущен цикл по каналу с задачами(`task`).
Принцип действия следующий: как только в канале появляется задача(task), она попадет в обработку в одну из горутин, на очередной итерации цикла исполняется там, а результат(error) обрабатывается

Как только такой механизм запущен, остаётся только передавать задачи(`task`) из слайса в этот канал

2022-01-28 15:35 UTC, agneum approved these changes
Спасибо за правки. Принято - 10/10

2022-01-31 21:01 UTC, merged